# Generated by Django 2.2.3 on 2019-07-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='lotsize',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
